### ISSUE TITLE
About drqn

### ISSUE THREAD

**Issue by hailuoS** [marctuscher/DRQN-tensorflow#3]
Thanks for your code, but I meet some problems.I ran the code used drqn but I found it ran much slower than dqn and the result was also worse than dqn, did I make some mistakes?

**Comment by marctuscher** [comment]
Yes, you are right. DRQN takes much longer to train than DQN. This is caused by the increased complexity of training a LSTM in addition to the other layers. Furthermore, I doubt that [this](https://github.com/marctuscher/DRQN-tensorflow/blob/bca74ff3acd7b35b744db42940e5524b8349dd1a/src/networks/drqn.py#L136) function is the most efficient way to train a DQRN in tensorflow. Unfortunately, I'm not able to dig into this due to other time consuming projects.

Since DRQN has more parameters and the training is also slower than DQN, it is natural that DQN outperforms DRQN after training for the same duration. Further, if training on an environment where 4 stacked frames are enough to generate a [Markov state](http://www0.cs.ucl.ac.uk/staff/d.silver/web/Teaching_files/MDP.pdf) it is unlikely for DRQN to outperform DQN at all.
