### ISSUE TITLE
Bootstrapped Sequential Updates

### ISSUE THREAD

**Issue by Joll123** [marctuscher/DRQN-tensorflow#5]
Do you try to train model by Bootstrapped Sequential Updates? I do not know how to choose the batch and I will appreciate it if you can help me.

**Comment by marctuscher** [comment]
You mean how to choose the minimum history of a state to be updated and the number of consecutive states to update? 

 I've explained some of my choices here:

https://github.com/marctuscher/DRQN-tensorflow/issues/2

Let me know if this helps!

**Comment by Joll123** [comment]
I want to train my network from start to end of one episode(Bootstrapped Sequential Updates). Should I choose one episode or many episodes for batch.

**Comment by marctuscher** [comment]
I didn't train a model using bootstrapped sequential updates, but with some modifications it should be possible.

First, you should modify the replay memory to directly sample complete episodes at random from it. Training on batches of episodes is definitely advisable, depending on your GPU memory. It should also be possible to use some kind of unrolled version of the LSTM for training, which would improve your training speed (but this also depends on the amount of available GPU memory). 

Since you really feed a lot of information (biased by the policy it was sampled from), be careful with your training frequency to keep the bias low.

**Comment by Joll123** [comment]
Thanks for your reply.
Because the steps for each episode are different, can a batch contain only one complete episode? Do you know how to solve it?

**Comment by marctuscher** [comment]
You could just use a batch size of 1 and use a dynamic RNN (https://www.tensorflow.org/api_docs/python/tf/keras/layers/RNN), which handles varying sequence lengths automatically.  Or the tf1 version of it (https://www.tensorflow.org/api_docs/python/tf/compat/v1/nn/dynamic_rnn).

**Comment by Joll123** [comment]
Thank you.
I have modified the replay memory to directly sample one complete episode at random from it to train, but train failed.
